export { AuthRestoreGate } from './auth-restore-gate'
export {
  clearAuthSession,
  ensureAuthSession,
  getCurrentCapabilities,
  getCurrentOrganizations,
  getCurrentUser,
  getSafeAuthRedirect,
  initializeAuthentication,
  listActiveSessions,
  login,
  logout,
  refreshSession,
  resetAuthRuntimeForTests,
  restoreSession,
  revokeSession,
} from './auth-service'
export {
  useActiveSessions,
  useCurrentCapabilities,
  useCurrentOrganization,
  useCurrentOrganizations,
  useCurrentUser,
  useIsAuthenticated,
  useLogin,
  useLogout,
  useRevokeSession,
  useSetCurrentOrganizationId,
} from './auth-hooks'
export {
  getAuthOrganizationPlanLabel,
  getAuthUserAvatar,
  getAuthUserDisplayName,
  getAuthUserEmail,
  getAuthUserGreetingName,
  getAuthUserInitials,
  getAuthUserRoleLabel,
} from './current-user-display'
export type {
  AuthCapability,
  AuthContext,
  AuthOrganization,
  AuthSession,
  AuthStatus,
  AuthTokenPayload,
  AuthTokens,
  AuthUser,
  LoginRequest,
  LoginResponse,
  RefreshRequest,
  RefreshResponse,
} from './types'
